# Commitment Service Spring Boot Application YAML
# Application info
info:
  app:
    artifact: ${project.artifactId}
    name: ${project.name}
    description: ${project.description}
    version: ${project.version}

# Spring Boot Actuator properties
endpoints:
  shutdown:
    enabled: true
  health:
    enabled: true

# Spring Boot port
server:
    port: 8888

---
spring:
  application:
    name: CodeChallenge062717
  sleuth:
    sampler:
      percentage: 1
    keys:
      http:
        headers: "X-Trace-Id,X-Span-Id,X-Context-Session-Id,X-Context-Request-Id,X-Context-Trace-Id,X-Context-Account-Id,X-Context-Customer-Id,X-Context-Order-Id,X-Context-Agent-Id"
    enabled: true
    stream:
      enabled: false
    log:
      json:
        enabled: true

# CF Application info
application:
  name: CodeChallenge062717
  instance: 1
eureka:
  instance:
    instanceId: CodeChallenge062717-local
    hostname: localhost:8888
#    nonSecurePort: 80
    nonSecurePortEnabled: false
#    securePort: 443
    securePortEnabled: false
    homePageUrl: http://${eureka.instance.hostname}/
    statusPageUrl: http://${eureka.instance.hostname}/metrics
    healthCheckUrl: http://${eureka.instance.hostname}/health
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: https://eureka:eureka@eureka-dev.dish.com/eureka/

configuredEnvironment: default